### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jubayer98** [morrislab/pairtree#32]
Traceback (most recent call last):
  File "(...)/pairtree/pairtree/bin/pairtree", line 177, in <module>
    main()
  File "(...)/pairtree/pairtree/bin/pairtree", line 141, in main
    parallel,
  File "(...)/pairtree/pairtree/bin/../lib/tree_sampler.py", line 643, in sample_trees
    raise exception
OSError: (...)/pairtree/pairtree/bin/../lib/projectppm/bin/libprojectppm.so: cannot open shared object file: No such file or directory
Sampling trees:   0%|          | 0/6000 [00:11<?, ?tree/s]    

Do not find any clue regarding this error.

**Comment by ethanumn** [comment]
Hi there -- 

It looks like the _projectppm_ project wasn't cloned and installed properly. Please refer to our [STAR protocols paper](https://www.sciencedirect.com/science/article/pii/S266616672200586X), specifically the _Troubleshooting_ and _Clone our repository and install requirements_ sections. They provide directions and problem solving techniques related to cloning and building the _projectppm_ software.

You can also refer to Section (2) of [this section of our README](https://github.com/morrislab/pairtree#installing-pairtree).

Please let me know if this solves your problem.

- Ethan

**Comment by jubayer98** [comment]
Hi Ethan,

Thanks for your prompt response. The problem actually being solved. Thanks for your suggestion and relevant sources.

- Jubayer

**Comment by jubayer98** [comment]
> Hi there --
> 
> It looks like the _projectppm_ project wasn't cloned and installed properly. Please refer to our [STAR protocols paper](https://www.sciencedirect.com/science/article/pii/S266616672200586X), specifically the _Troubleshooting_ and _Clone our repository and install requirements_ sections. They provide directions and problem solving techniques related to cloning and building the _projectppm_ software.
> 
> You can also refer to Section (2) of [this section of our README](https://github.com/morrislab/pairtree#installing-pairtree).
> 
> Please let me know if this solves your problem.
> 
> * Ethan

Hi Ethan,

Thanks for your prompt response. The problem actually being solved. Thanks for your suggestion and relevant sources.

- Jubayer
